### ISSUE TITLE
fails to build with text-2.1.2

### ISSUE THREAD

**Issue by juhp** [tonyday567/box#14]
For Stackage Nightly with ghc-9.10.2:

```
       Building library for box-0.9.3.2...                                                                     12:58:25 [846/954403]
       [ 1 of 10] Compiling Box.Codensity                                                                                           
       [ 2 of 10] Compiling Box.Functor                                                                                             
       [ 3 of 10] Compiling Box.Emitter                                                                                             
       [ 4 of 10] Compiling Box.Committer                                                                                           
       [ 5 of 10] Compiling Box.Box                                                                                                 
       [ 6 of 10] Compiling Box.Queue                                                                                               
       [ 7 of 10] Compiling Box.Connectors                                                                                          
       [ 8 of 10] Compiling Box.IO                                                                                                  
       /home/curators/work/unpack-dir/unpacked/box-0.9.3.2-294160b45cc2014ade45dab6bdd19f5dcf8e95e51f38d173923b9ac7d34ae401/src/Box/
IO.hs:124:37: error: [GHC-87543]                                                                                                    
           Ambiguous occurrence ‘show’.                                                                                             
           It could refer to                                                                                                        
              either ‘Text.show’,                                                                                                   
                     imported from ‘Data.Text’ at src/Box/IO.hs:49:1-38,                                                            
                  or ‘Prelude.show’,                                                                                                
                     imported from ‘Prelude’ at src/Box/IO.hs:53:1-14                                                               
                     (and originally defined in ‘ghc-internal-9.1002.0:GHC.Internal.Show’).                                         
           |                                                                                                                        
       124 | showStdout = contramap (Text.pack . show) toStdout                                                                     
           |                                     ^^^^                                                                               
                                                                                                                                    
       /home/curators/work/unpack-dir/unpacked/box-0.9.3.2-294160b45cc2014ade45dab6bdd19f5dcf8e95e51f38d173923b9ac7d34ae401/src/Box/
IO.hs:222:30: error: [GHC-87543]                                                                                                    
           Ambiguous occurrence ‘show’.                                                                                             
           It could refer to                                                                                                        
              either ‘Text.show’,                                                                                                   
                     imported from ‘Data.Text’ at src/Box/IO.hs:49:1-38,                                                            
                  or ‘Prelude.show’,                                                                                                
                     imported from ‘Prelude’ at src/Box/IO.hs:53:1-14
                     (and originally defined in ‘ghc-internal-9.1002.0:GHC.Internal.Show’).
           |
       222 |   Prelude.putStrLn (label <> show a)
           |                              ^^^^
        
       /home/curators/work/unpack-dir/unpacked/box-0.9.3.2-294160b45cc2014ade45dab6bdd19f5dcf8e95e51f38d173923b9ac7d34ae401/src/Box/
IO.hs:228:30: error: [GHC-87543]
           Ambiguous occurrence ‘show’.
           It could refer to
              either ‘Text.show’,
                     imported from ‘Data.Text’ at src/Box/IO.hs:49:1-38,
                  or ‘Prelude.show’,
```

**Comment by tonyday567** [comment]
#15 fixes which is box-0.9.3.3 Thank you for the report!
